### ISSUE TITLE
Multiple Ruler in one VC

### ISSUE THREAD

**Issue by noujan** [danjiang/DTRuler#6]
Hey, 
I have 3 Rulers in one ViewController. How can I recognize which one is changing?

func didChange(on ruler: DTRuler, withScale scale: DTRuler.Scale) {
        HeightLabel.text = scale.minorTextRepresentation()
        WeightLabel.text = scale.minorTextRepresentation()
        AgeLabel.text = scale.minorTextRepresentation()
     }

with this didChange, all labels are changing. I cannot detect which Ruler changed.

I have heightRuler, weightRuler and ageRuler. how can I create have 3 seperate didChange funcs?
thanks

**Comment by danjiang** [comment]
You can check which ruler by `ruler === heightRuler`.
